# Generated by Django 5.0.2 on 2024-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makul', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=250)),
                ('tenggat', models.DateTimeField(verbose_name='Tenggat Waktu')),
            ],
        ),
    ]
